### ISSUE TITLE
[Feature] Add eslint-loader

### ISSUE THREAD

**Issue by neo** [Jam3/nyg-nextjs#32]
now we're doing eslint separately from the build process, would be great that it's integrated into webpack.

one benefit I could see is that eslint would error out during development and showup as an error overlay in browser.

**Comment by neo** [comment]
the nextjs team claimed that they might add it: https://github.com/zeit/next.js/issues/7936#issuecomment-568910990

**Comment by miguelmoraleda** [comment]
@grez96 is gonna reach out to Iran to ask for his opinion about adding this feature.

**Comment by grez96** [comment]
https://github.com/Jam3/nyg-nextjs/pull/44

**Comment by namniak** [comment]
merged https://github.com/Jam3/nyg-nextjs/pull/44
