### ISSUE TITLE
[Feature] Integrate "jam3/react-ui" components.

### ISSUE THREAD

**Issue by namniak** [Jam3/nyg-nextjs#53]
Integrate `jam3/react-ui` library. 

**Min requirements:**

- Replace existing UI components such as `Nav`, `Footer`, `RotateScreen` to keep it modular.

**Extra effort:**
- Bring in and integrate, `HamburgerMenu`, `PageOverlay`

**Comment by artemleznikov** [comment]
Since the 'Nav' and 'Footer' components differ greatly between projects in terms of design and functionality, would we still want those as part of the `jam3/react-ui` library? I feel like future dev's will just create those components from scratch anyways as it will easier.

**Comment by namniak** [comment]
yeah i'm kinda always sceptical about value of reusable (pure UI) components such as those but we always come back to this discussion 🙂
